### ISSUE TITLE
Get together as a team

### ISSUE THREAD

**Issue by sswaans** [StanfordCS194/Luna#1]
Hi folks,

Please arrange to meet one another, find a good SGM time that works for you and get after the [Startup Your Team](https://github.com/StanfordCS194/Home/blob/master/Startup-Your-Team.md) assignment.

Jay

**Comment by averwillow** [comment]
is there a way to view our group members on the github?

**Comment by kjue25** [comment]
If you click on Settings (from within StanfordCS194/Team-15) > Collaborators & teams, that should show you all of your team members.  Some may not have yet accepted their GitHub invitations (which is why they weren't assigned this issue).
